export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SYNC = 'FETCH_CATEGORIES_SYNC';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const REQUESTING_CONTACT_INFORMATION = 'REQUESTING_CONTACT_INFORMATION';
export const SET_CONTACT_FORM_FEEDBACK = 'SET_CONTACT_FORM_FEEDBACK';

export const REQUESTING_CAREERS_INFORMATION = 'REQUESTING_CAREERS_INFORMATION';
export const SET_CAREERS_FORM_FEEDBACK = 'SET_CAREERS_FORM_FEEDBACK';
export const SET_CAREERS_FORM_VALUES = 'SET_CAREERS_FORM_VALUES';

export const CHANGE_TAB = 'CHANGE_TAB';
export const REQUESTING_PRODUCT_INFORMATION = 'REQUESTING_PRODUCT_INFORMATION';
export const SET_PRODUCT_FORM_FEEDBACK = 'SET_PRODUCT_FORM_FEEDBACK';
