export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FILTER_SELECTED = 'FILTER_SELECTED';

export const REQUESTING_CONTACT_INFORMATION = 'REQUESTING_CONTACT_INFORMATION';
export const SET_CONTACT_FORM_FEEDBACK = 'SET_CONTACT_FORM_FEEDBACK';

export const REQUESTING_REVIEW_COMMENT = 'REQUESTING_REVIEW_COMMENT';
export const SET_REVIEW_FORM_FEEDBACK = 'SET_REVIEW_FORM_FEEDBACK';
export const SET_REVIEW_FORM_SUCCESSFUL = 'SET_REVIEW_FORM_SUCCESSFUL';

export const REQUESTING_ADD_TO_CART = 'REQUESTING_ADD_TO_CART';
export const SET_ADD_TO_CART_FORM_FEEDBACK = 'SET_ADD_TO_CART_FORM_FEEDBACK';

export const REQUESTING_CAREERS_INFORMATION = 'REQUESTING_CAREERS_INFORMATION';
export const SET_CAREERS_FORM_FEEDBACK = 'SET_CAREERS_FORM_FEEDBACK';
export const SET_CAREERS_FORM_VALUES = 'SET_CAREERS_FORM_VALUES';

export const CHANGE_TAB = 'CHANGE_TAB';
export const REQUESTING_PRODUCT_INFORMATION = 'REQUESTING_PRODUCT_INFORMATION';
export const SET_PRODUCT_FORM_FEEDBACK = 'SET_PRODUCT_FORM_FEEDBACK';
